### PR TITLE
Use local IPFS gateway if available

### PR DESCRIPTION
**Pull request by fnkr**
Relates to https://github.com/ipfs-search/ipfs-search/pull/58.

### CODE REVIEW

**Comment by dokterbob** [comment]
Hey,

Thanks again! But ain't that the same problem, again? Really, doing two requests for every search degrades the user experience, badly. Just do it on page load!

M
-- 
Verstuurd vanaf mijn Android apparaat met K-9 Mail. Excuseer mijn beknoptheid.

**Comment by madnificent** [comment]
Hi,

Thanks for jumping in on the frontend!  Great to have you as a contributor.  The code looks cleanly readable at first sight. Accessing the local IPFS daemon is certainly a nice feature.  I think a semi-correct implementation is tricky though.

Querying the local host (or network) of a user without them explicitly asking for it seems to be bad behaviour.  Especially  because the IPFS service is running on such a common port (which many users will likely change).  I suspect some malware scanners will detect this.

We could implement this behaviour by implementing a settings page (possibly based on https://github.com/jerel/ember-storage) in which users can set their preferred gateway.  This would have the added benefit that they could run a single gateway on their local network.

The 'correct' solution probably lies in browsers understanding the IPFS protocol, rather than us hacking around it.  It is a terribly idea for all ipfs-related web applications to build their own workarounds to accessing the local node.  We will end up with different implementations, and the IPFS-community will to be able to shift away from them without a lot of pain.  I find the nicest approach around this to be the IPFS Companion browser addon (https://addons.mozilla.org/en-US/firefox/addon/ipfs-companion/) as this works across websites.

Unless there is a strong urge towards implementing a solution for this problem in each web application separately, I would urge against discovering the local node.  If there is a strong feeling towards detecting the local node, I suggest we do so in a configuration page, store the contents in local storage, and explicitly label it as a workaround we currently execute.

**Comment by fnkr** [comment]
Hi, thank you both for your response.

> Really, doing two requests for every search degrades the user experience, badly.

@dokterbob, I thought about that for the other merge request as well. I came to the conclusion that it would be better to do the check more often. Many people leave their browser tabs open for long periods. The local IPFS daemon might go away at some point (or the opposite), the app should reflect that. Also the check does not have any noticeable performance impact.

1) IPFS is distributed with this block pinned, so unless the user manually removes the pin (`ipfs pin rm`) and then removes the block as well (`ipfs block rm`) it is already there. I did some performance testing and IPFS always delivered within 9ms at max. The search query takes way longer (sometimes >1s).

2) The XHR request for the IPFS daemon check is asynchronous with the search XHR request. The search does not wait for the daemon check to be completed. If the daemon delivers in time it will be used, otherwise it won't. I've also added a timeout for the check (50ms).

> The 'correct' solution probably lies in browsers understanding the IPFS protocol, rather than us hacking around it. It is a terribly idea for all ipfs-related web applications to build their own workarounds to accessing the local node. We will end up with different implementations, and the IPFS-community will to be able to shift away from them without a lot of pain.

@madnificent I agree that browser integration would be best. As I understand it the ping file was made for the purpose of checking if the gateway works. IPFS uses it in their own tests too.

> Querying the local host (or network) of a user without them explicitly asking for it seems to be bad behaviour. Especially because the IPFS service is running on such a common port (which many users will likely change).

Alternatively, we could query http://localhost:5001/api/v0/config/Addresses.Gateway (which is a less common port) and use the gateway from the json response, which looks like this:

```js
{"Key":"Addresses.Gateway","Value":"/ip4/127.0.0.1/tcp/8080"}
```

> Unless there is a strong urge towards implementing a solution for this problem in each web application separately, I would urge against discovering the local node. If there is a strong feeling towards detecting the local node, I suggest we do so in a configuration page, store the contents in local storage, and explicitly label it as a workaround we currently execute.

I agree that querying localhost may not be the fine British style but using a third party as a proxy is not great either.

1. It leads the idea behind IPFS ad absurdum and basically reverts half it's benefits.

2. Routing all traffic from a user through a single centralised gateway (especially one without disclosed privacy policy) is a privacy disaster.

> If there is a strong feeling towards detecting the local node, I suggest we do so in a configuration page, store the contents in local storage, and explicitly label it as a workaround we currently execute.

That would be a valid option, although I think it should not be hidden in a settings page, in my experience most users never discover such a page.

**Comment by madnificent** [comment]
Hi,

I think I fully agree with you on just about every statement you made.  It is not ≠≠  Can you motivate why we shouldn't push people towards using

**Comment by madnificent** [comment]
Hi,

Your vision on how IPFS should be used is clear and I strongly sympathize with it.  We should not depend on a single gateway to exist for a distributed web.  We both agree that we should, in the future, have a solid integration with IPFS rather than haphazardly implemented workarounds.

I wonder where you feel the forwarding of IPFS companion to be insufficient.  The idea here is that it hijacks requests which are made to ipfs.io/ipfs/... and redirects them to a gateway of your choosing (likely localhost:8080).  This browser addon also detects whether your node is up, and informs you about it.  Perhaps it would be more future-proof to guide our users in that path, as it can be a more-or-less permanent solution (at least, we can depend on another organization to handle this across websites, giving users a single point of configuration).

There are cases where this would not be sufficient, perhaps you're encountering one of these.  My Android phone doesn't have this sort of feature enabled (but then again, it doesn't run an IPFS node of its own either).  Safari does not have such an addon available, and many other browsers will fall under this category.  Are you in this sort of situation?  Do we aim to cater for these situations with workarounds and maintain them at this stage?

Could you be so kind to look into [IPFS Companion](https://github.com/ipfs-shipyard/ipfs-companion) and share your thoughts on this approach?

**Pull request closed without merging**
