### PR TITLE
Refreshed API interface

### PR DESCRIPTION
**Pull request by Lucas-Kohorst**
- Refreshed look and feel to the API page
- Brought all known API routes together with curl examples and explanations

### CODE REVIEW

**Comment by dokterbob** [comment]
Hey Lucas,

Thanks for the contrib! Great initiative!

However, the proposed changes would require some external tool to change the page whereas the originals could be edited manually by hand without any additional skills, documentation or knowledge.

I am not generally against using tools, as a matter of fact, this could be an excellent occasion. But I prefer being conscious of it, particularly with regard to maintenance.

Could you:
a) Specify which tool you'd like to elect for the task, which other tools have been considered and why you think this is the best one? Specifically, I'd like to know what significant benefits it would offer over plain HTML and/or Markdown given the specific requirements; displaying code examples, their results and explaining them. Also, please explain why you believe this tooling will still be maintained ~2-5 years from now, or how we might easily replace it when it is not.
b) If I follow your conclusion on the choice of tooling; could you please add a README.md describing how the API docs might be build and what the requirements are, as well as the source content?

Thanks!
Mathijs

**Comment by Lucas-Kohorst** [comment]
Hi, 

I understand that the initial file I committed had was hard to edit and iterate on. It was developed using [Docz](https://github.com/doczjs/docz) which generates a gatsby site from a markdown file. 

Since the file is pretty unreadable and the process to generate new documentation or change a few lines requires additional knowledge and tooling that after consideration does not have that many benefits for what the page is. I just committed changes so that the API page is in readable .html that can be easily edited and styled with .css from [Markdown Retro](https://github.com/markdowncss/retro). 

Screen Shot 2019-11-22 at 7 17 47 AM

The HTML is easily editable for quick iterations and maintenance. 

Thanks, I think this is a fantastic project!
-Lucas

**Comment by madnificent** [comment]
Could we render the md files in the frontend directly?  We can keep the README.md in the frontend repository or fetch it from elsewhere.  Does that sound like a plan?

**Comment by madnificent** [comment]
I don't know by heart how this is currently integrated, but it seems feasible to integrate the HTML and CSS into the relevant handlebars and CSS file too.  We might hit into some CSS struggles there but I can also scope that for now.

If @vandrongelen is good with this, I'll take a poke to see if things wire up easily.

**Comment by dokterbob** [comment]
I've now created a proper [API spec](https://github.com/ipfs-search/ipfs-search-api/blob/master/openapi.yaml) which automatically [generates extensive documentation](https://github.com/ipfs-search/ipfs-search-api/tree/master/docs).

**Pull request closed without merging**
